variables:
  vcpkgPackages: 'sqlite3'
  system.debug: true
  thisRepo: 'CppBuildTasks-Validation'
  vcpkgGitCommitId: 2019.10
  vcpkgTriplet: 'x64-osx' # Needed as the triplet is not specified on the command line.

resources:
  repositories:
  - repository: vcpkg
    type: github
    name: microsoft/vcpkg
    endpoint: vcpkg
    ref: refs/tags/$(vcpkgGitCommitId)

jobs:

- job: macos_hosted
  pool:
    vmImage: 'macOS-10.14'
    
  steps:
    - checkout: self
      submodules: recursive
    - checkout: vcpkg
      displayName: "Checkout vcpkg in '$(Build.SourcesDirectory)/vcpkg'"
    - template: ../templates/install-gcc-macos.yml
    - task: Cache@2
      displayName: Cache vcpkg
      inputs:
        key: $(vcpkgPackages) | "$(vcpkgGitCommitId)" | "$(Agent.OS)"
        path: '$(Build.SourcesDirectory)/vcpkg'
    - task: lucappa.cmake-ninja-vcpkg-tasks.d855c326-b1c0-4d6f-b1c7-440ade6835fb.run-vcpkg@0
      displayName: 'Run vcpkg on the submodule without updating'
      inputs:
        vcpkgTriplet: $(vcpkgTriplet)
        vcpkgArguments: '$(vcpkgPackages)'
        vcpkgDirectory: '$(Build.SourcesDirectory)/vcpkg'
        cleanAfterBuild: true
        doNotUpdateVcpkg: true
    - task: lucappa.cmake-ninja-vcpkg-tasks.d855c326-b1c0-4d6f-b1c7-440ade6835fb.run-vcpkg@0
      displayName: 'Run vcpkg on the directory (indipendently check-ed out) with no update'
      inputs:
        vcpkgTriplet: $(vcpkgTriplet)
        vcpkgArguments: '$(vcpkgPackages)'
        vcpkgDirectory: '$(Build.SourcesDirectory)/vcpkg'
        cleanAfterBuild: true
        doNotUpdateVcpkg: true
    - task: lucappa.cmake-ninja-vcpkg-tasks.f2b1ec7d-bc54-4cc8-b9ed-1bc7f37c9dc6.run-cmake@0
      displayName: 'Run CMake with Ninja'
      inputs:
        cmakeListsTxtPath: '$(thisRepo)/cmakeliststxt/CMakeLists.txt'
        useVcpkgToolchainFile: true
        buildWithCMakeArgs: '-- -v'

