jobs:

- job: macos_hosted
  pool:
    vmImage: 'macOS-10.14'
    
  variables:
    system.debug: true
    vcpkgCommitId: 0591528cbfde14ccfd3900c3fb19aba382c05349

  steps:
    - template: ../templates/install-gcc-macos.yml
    - task: Cache@2
      displayName: Cache vcpkg
      inputs:
        key: $(Build.SourcesDirectory)/cmakeliststxt/vcpkg_x64-osx.txt | "$(vcpkgCommitId)" | "$(Agent.OS)"
        path: '$(Build.BinariesDirectory)/vcpkg'
    - task: lucappa.cmake-ninja-vcpkg-tasks.d855c326-b1c0-4d6f-b1c7-440ade6835fb.run-vcpkg@0
      displayName: 'Run vcpkg'
      inputs:
        vcpkgArguments: '@$(Build.SourcesDirectory)/cmakeliststxt/vcpkg_x64-osx.txt'
        vcpkgGitCommitId: $(vcpkgCommitId)
        vcpkgGitURL: https://github.com/lukka/vcpkg.git
    - task: lucappa.cmake-ninja-vcpkg-tasks.f2b1ec7d-bc54-4cc8-b9ed-1bc7f37c9dc6.run-cmake@0
      displayName: 'Run CMake with Ninja'
      inputs:
        cmakeListsTxtPath: '$(Build.SourcesDirectory)/cmakeliststxt/CMakeLists.txt'
        useVcpkgToolchainFile: true
        buildWithCMakeArgs: '-- -v'