jobs:

- job: ubuntu_hosted
  pool:
    vmImage: 'ubuntu-latest'

  variables:
    vcpkgPackages: 'sqlite3'
    system.debug: true
    vcpkgCommitId: 8a9a97315aefb3f8bc5d81bf66ca0025938b9c91

  steps:
    - task: lucappa.cmake-ninja-vcpkg-tasks.d855c326-b1c0-4d6f-b1c7-440ade6835fb.run-vcpkg@0
      displayName: 'Run vcpkg'
      inputs:
        vcpkgTriplet: 'x64-linux'
        vcpkgArguments: '$(vcpkgPackages)'
        vcpkgGitCommitId: '$(vcpkgCommitId)'
    - task: lucappa.cmake-ninja-vcpkg-tasks.f2b1ec7d-bc54-4cc8-b9ed-1bc7f37c9dc6.run-cmake@0
      displayName: 'Run CMake with Ninja'
      inputs:
        cmakeListsTxtPath: 'cmakeliststxt/CMakeLists.txt'
        useVcpkgToolchainFile: true
        vcpkgTriplet: '$(RUNVCPKG_VCPKG_TRIPLET)'
        buildWithCMakeArgs: '-- -v'
        ninjaDownloadUrl: https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip

