# Copyright (c) 2019-2020-2021-2022 Luca Cappa
# Released under the term specified in file LICENSE.txt
# SPDX short identifier: MIT
name: hosted-advanced-dumplogs-autocache
on: [push]

jobs:

  vcpkg-fails:
    name: ${{ matrix.os }}-vcpkg-log-collection-validation
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
            vcpkgCommitId: '5568f110b509a9fd90711978a7cb76bae75bb092'
            vcpkgPackages: 'zlib bzip2 liblzma zstd'
          - os: ubuntu-latest
            triplet: x64-linux
            vcpkgCommitId: '5568f110b509a9fd90711978a7cb76bae75bb092'
            vcpkgPackages: 'zlib bzip2 liblzma zstd'
          - os: macos-latest
            triplet: x64-osx
            vcpkgCommitId: '5568f110b509a9fd90711978a7cb76bae75bb092'
            vcpkgPackages: 'zlib bzip2 liblzma zstd'

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: dir
        run: find $RUNNER_WORKSPACE
        shell: bash
      - name: Run vcpkg and dump its failure log
        uses: lukka/run-vcpkg@v10.1
        with:
          vcpkgArguments: '${{ matrix.vcpkgPackages }}'
          vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
          vcpkgTriplet: '${{ matrix.triplet }}'
          vcpkgGitCommitId: '${{ matrix.vcpkgCommitId }}'
        continue-on-error: true

  cmake-fails:
    name: ${{ matrix.os }}-cmake-log-collection-validation
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
            vcpkgCommitId: '30124253eecff36bc90f73341edbfb4f845e2a1e'
            vcpkgPackages: 'sqlite3'
            configuration: 'x64.*'
          - os: ubuntu-latest
            triplet: x64-linux
            vcpkgCommitId: '30124253eecff36bc90f73341edbfb4f845e2a1e'
            vcpkgPackages: 'sqlite3'
            configuration: '.*Linux.*'
          - os: macos-latest
            triplet: x64-osx
            vcpkgCommitId: '30124253eecff36bc90f73341edbfb4f845e2a1e'
            vcpkgPackages: 'sqlite3'
            configuration: '.*Linux.*'

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - uses: lukka/get-cmake@latest
      - name: dir
        run: find $RUNNER_WORKSPACE
        shell: bash
      - name: Restore artifacts, or Run vcpkg, build and cache artifacts
        uses: lukka/run-vcpkg@v10.1
        id: runvcpkg
        with:
          vcpkgArguments: '${{ matrix.vcpkgPackages }}'
          vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
          vcpkgTriplet: '${{ matrix.triplet }}'
          vcpkgGitCommitId: '${{ matrix.vcpkgCommitId }}'
      - name: Prints output of run-vcpkg's task
        run: echo "root='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}', triplet='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_TRIPLET_OUT }}' "
      - name: Run CMake and dump its failure log
        continue-on-error: true
        uses: lukka/run-cmake@main
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/cmakeliststxt/CMakeLists.txt'
          buildDirectory: '${{ runner.workspace }}/b/dump_log'
          cmakeAppendedArgs: '-DCMAKE_CXX_COMPILER=abc'
          buildWithCMake: false
      - name: dir
        run: find $RUNNER_WORKSPACE
        shell: bash

